org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.21
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=weather2overcastlighting
mod_name=Weather2 Overcast Lighting
mod_license=LGPL 2.1
mod_version=1.0.0
mod_group_id=thaurane.weather2overcastlighting
mod_authors=thaurane
mod_description=Adds local overcast sky and world darkening based on Weather2 layer 1 cloud coverage.
